//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new car.
        /// </summary>
        public static string AddNewCar {
            get {
                return ResourceManager.GetString("AddNewCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string addString {
            get {
                return ResourceManager.GetString("addString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your car info here!.
        /// </summary>
        public static string AddYourCarInfoHere {
            get {
                return ResourceManager.GetString("AddYourCarInfoHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Class.
        /// </summary>
        public static string CarClass {
            get {
                return ResourceManager.GetString("CarClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Econom class.
        /// </summary>
        public static string CarClassEconom {
            get {
                return ResourceManager.GetString("CarClassEconom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General class.
        /// </summary>
        public static string CarClassGeneral {
            get {
                return ResourceManager.GetString("CarClassGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium class.
        /// </summary>
        public static string CarClassPremium {
            get {
                return ResourceManager.GetString("CarClassPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car manufacture Date.
        /// </summary>
        public static string CarManufactureDate {
            get {
                return ResourceManager.GetString("CarManufactureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Name.
        /// </summary>
        public static string CarName {
            get {
                return ResourceManager.GetString("CarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Number.
        /// </summary>
        public static string CarNumber {
            get {
                return ResourceManager.GetString("CarNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Occupation.
        /// </summary>
        public static string CarOccupation {
            get {
                return ResourceManager.GetString("CarOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Petrol Consumption.
        /// </summary>
        public static string CarPetrolConsumption {
            get {
                return ResourceManager.GetString("CarPetrolConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel.
        /// </summary>
        public static string CarPetrolDiesel {
            get {
                return ResourceManager.GetString("CarPetrolDiesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal-80.
        /// </summary>
        public static string CarPetrolNormal {
            get {
                return ResourceManager.GetString("CarPetrolNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string CarPetrolOther {
            get {
                return ResourceManager.GetString("CarPetrolOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 95.
        /// </summary>
        public static string CarPetrolPremium {
            get {
                return ResourceManager.GetString("CarPetrolPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 92.
        /// </summary>
        public static string CarPetrolRegular {
            get {
                return ResourceManager.GetString("CarPetrolRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 98.
        /// </summary>
        public static string CarPetrolSuper {
            get {
                return ResourceManager.GetString("CarPetrolSuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petrol Type.
        /// </summary>
        public static string CarPetrolType {
            get {
                return ResourceManager.GetString("CarPetrolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car registration.
        /// </summary>
        public static string CarRegistration {
            get {
                return ResourceManager.GetString("CarRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car State.
        /// </summary>
        public static string CarState {
            get {
                return ResourceManager.GetString("CarState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On repair.
        /// </summary>
        public static string CarStateRepairing {
            get {
                return ResourceManager.GetString("CarStateRepairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working.
        /// </summary>
        public static string CarStateWorking {
            get {
                return ResourceManager.GetString("CarStateWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string deleteString {
            get {
                return ResourceManager.GetString("deleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string editString {
            get {
                return ResourceManager.GetString("editString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is empty.
        /// </summary>
        public static string EmptyEmail {
            get {
                return ResourceManager.GetString("EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty.
        /// </summary>
        public static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName is empty.
        /// </summary>
        public static string EmptyUserName {
            get {
                return ResourceManager.GetString("EmptyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName or Email is already exists.
        /// </summary>
        public static string LoginEmailExist {
            get {
                return ResourceManager.GetString("LoginEmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To main menu.
        /// </summary>
        public static string MainLink {
            get {
                return ResourceManager.GetString("MainLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal cabinet.
        /// </summary>
        public static string PersonalCabinet {
            get {
                return ResourceManager.GetString("PersonalCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportViewer.
        /// </summary>
        public static string ReportViewer {
            get {
                return ResourceManager.GetString("ReportViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set date.
        /// </summary>
        public static string Setdate {
            get {
                return ResourceManager.GetString("Setdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set VIP Status.
        /// </summary>
        public static string SetVIPStatusPage {
            get {
                return ResourceManager.GetString("SetVIPStatusPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is less than 5 characters.
        /// </summary>
        public static string ShortPassword {
            get {
                return ResourceManager.GetString("ShortPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName is less than 4 characters.
        /// </summary>
        public static string ShortUserName {
            get {
                return ResourceManager.GetString("ShortUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update profile.
        /// </summary>
        public static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
